### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by michellejanosi** [amandeepmittal/nodejs-tweet#1]
I'm getting this error when running bot.js:

TypeError: Cannot read property 'id_str' of undefined
var retweetId = data.statuses[0].id_str;

**Comment by amandeepmittal** [comment]
@michellejanosi are you passing data as a parameter to the callback function associated with getting Tweets for retweet not for the favorite tweet funcionality? 

```js
 Twitter.get('search/tweets', params, function(err, data) {   //passing data as parameter
      // if there no errors
        if (!err) {
          // grab ID of tweet to retweet
            var retweetId = data.statuses[0].id_str;
```

**Comment by michellejanosi** [comment]
Yes. This is in the retweet function.
```
function retweetLatest() {
    T.get('search/tweets', hashtagSearch, function(error, data)
```
I cloned your repo.

**Comment by amandeepmittal** [comment]
Are you using the same version of Twit as mentioned in my repo's `package.json`? TypeError is occurring but that doesn't make any sense. I found one link but I don't know it'd be helpful to you or not: Please check [this issue on Twit's Repo](https://github.com/ttezel/twit/issues/33).

It can an be an issue with your query (in your case the value of `hashtagSearch`) if `TypeError` is occurring.

**Comment by michellejanosi** [comment]
Good call on the version. Updated that but found the issue to be the `hashtagSearch` as you mentioned. Thank you so much for your help! 😊

**Comment by amandeepmittal** [comment]
@michellejanosi glad could be of any help.
